"""Deterministic org-wide diagram rendering from the compiled index (design D3/D4).

Pure function, same shape as ``docs.render_interface_docs()``: compiled index in, org diagram
markdown out. No LLM involvement — the content is mechanically derived from the compiled index's
``owner``/``producer``/``consumer`` data, so it can never disagree with the index that produced it
and is exempt from doc-drift checking by construction.

One ``## {repo}`` section per repo with at least one *external* interface (alphabetical), each with
a small relationship graph (this repo as center node, one node per related repo, one edge per
interface — not deduplicated across interfaces to the same repo) and a table of that repo's
external interfaces. Repos whose every interface is internal-only (design's exclusion rule: the
union of an interface's owner/producer/consumer repos names exactly one repo) get no section.
"""

import re
from pathlib import Path

from .config import DEFAULT_DIAGRAM_FORMAT

# Instance repo root, distinct from docs/{repo}/architecture.md (each child repo's own copy).
ORG_DIAGRAM_PATH = Path("docs") / "architecture.md"

_GENERATED_HEADER = (
    "<!-- Generated by panopticon.diagrams from the compiled interface index. Do not edit by hand:\n"
    "     rebuilt automatically on every merge to a child repo's default branch. -->"
)

_MERMAID_ID_RE = re.compile(r"[^A-Za-z0-9_]")


def _mermaid_id(repo):
    return "repo_" + _MERMAID_ID_RE.sub("_", repo)


def repo_set(entry):
    """The union of repo names in one interface entry's owner/producer/consumer (design's
    internal-only exclusion rule input)."""
    repos = set()
    owner = entry.get("owner")
    if owner:
        repos.add(owner["repo"])
    for role in ("producer", "consumer"):
        repos.update(robj["repo"] for robj in entry[role])
    return repos


def _other_repo_role(entry, other_repo):
    """`other_repo`'s role(s) for this interface entry — owner, producer, and/or consumer."""
    roles = []
    owner = entry.get("owner")
    if owner and owner["repo"] == other_repo:
        roles.append("owner")
    if any(robj["repo"] == other_repo for robj in entry["producer"]):
        roles.append("producer")
    if any(robj["repo"] == other_repo for robj in entry["consumer"]):
        roles.append("consumer")
    return roles


def relationships_for_repo(compiled, repo):
    """External-interface rows for `repo`: one row per (interface, other-repo) pair, sorted by
    interface name then other repo (design D4: per-interface, not deduplicated). Empty when every
    one of `repo`'s interfaces is internal-only."""
    rows = []
    for name in sorted(compiled.get("interfaces", {})):
        for entry in compiled["interfaces"][name]:
            repos = repo_set(entry)
            if len(repos) <= 1 or repo not in repos:
                continue
            produces = any(robj["repo"] == repo for robj in entry["producer"])
            consumes = any(robj["repo"] == repo for robj in entry["consumer"])
            direction = [d for d, flag in (("produces", produces), ("consumes", consumes)) if flag]
            if not direction:
                # repo owns this interface but neither produces nor consumes it itself.
                direction = ["owns"]
            for other in sorted(repos - {repo}):
                rows.append(
                    {
                        "name": name,
                        "type": entry["type"],
                        "direction": "/".join(direction),
                        "produces": produces,
                        "consumes": consumes,
                        "other_repo": other,
                        "other_role": "/".join(_other_repo_role(entry, other)) or "none",
                    }
                )
    return rows


def _mermaid_graph(repo, rows):
    lines = ["graph LR", f'    {_mermaid_id(repo)}["{repo}"]']
    seen = {repo}
    for row in rows:
        other = row["other_repo"]
        if other not in seen:
            lines.append(f'    {_mermaid_id(other)}["{other}"]')
            seen.add(other)
        label = row["name"]
        if row["consumes"] and not row["produces"]:
            lines.append(f"    {_mermaid_id(other)} -->|{label}| {_mermaid_id(repo)}")
        else:
            # produces (with or without also consuming), or owns-only: repo -> other.
            lines.append(f"    {_mermaid_id(repo)} -->|{label}| {_mermaid_id(other)}")
    return "\n".join(lines)


def _table(rows):
    lines = [
        "| Interface | Type | Direction | Other repo | Other repo's role |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        other = row["other_repo"]
        link = f"[{other}](docs/{other}/architecture.md)"
        lines.append(f"| `{row['name']}` | {row['type']} | {row['direction']} | {link} | {row['other_role']} |")
    return "\n".join(lines)


def render_org_diagram(compiled, diagram_format=None):
    """Deterministic org-diagram document (design D3/D4). `diagram_format` tags each repo
    section's fenced graph block (default: DEFAULT_DIAGRAM_FORMAT) — callers are responsible for
    rejecting unsupported formats before calling this (config.require_supported_diagram_format);
    this function only renders Mermaid graph syntax, the only implemented renderer."""
    fmt = diagram_format or DEFAULT_DIAGRAM_FORMAT
    repos = sorted(
        {r for entries in compiled.get("interfaces", {}).values() for entry in entries for r in repo_set(entry)}
    )
    lines = [_GENERATED_HEADER, "", "# Organization architecture", ""]
    any_section = False
    for repo in repos:
        rows = relationships_for_repo(compiled, repo)
        if not rows:
            continue
        any_section = True
        lines += [
            f"## {repo}",
            "",
            f"See this repo's own diagram: [docs/{repo}/architecture.md](docs/{repo}/architecture.md)",
            "",
            f"```{fmt}",
            _mermaid_graph(repo, rows),
            "```",
            "",
            _table(rows),
            "",
        ]
    if not any_section:
        lines += ["No cross-repo interface relationships yet.", ""]
    return "\n".join(lines)


def write_org_diagram(compiled, instance_root, diagram_format=None):
    path = Path(instance_root) / ORG_DIAGRAM_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_org_diagram(compiled, diagram_format), encoding="utf-8")
    return path
